# Chapter 6 行列

## 6.1 行列

### 要素から行列を生成する

Juliaでは行列を2次元配列で表現する．そのためには，各行の要素を空白で区切り，各行はセミコロンで区切って，最後に`[]`で全体を囲む．例えば$3\times 4$行列
$$
A = 
\begin{bmatrix}
0 & 1 & -2.3 & 0.1\\
1.3 & 4 & -0.1 & 0\\
4.1 & -1 & 0 & 1.7
\end{bmatrix}
$$
はJuliaでは以下のようになる．

In [1]:
A = [0.0  1.0 -2.3  0.1;
     1.3  4.0 -0.1  0.0;
     4.1 -1.0 0.0 1.7]

3×4 Array{Float64,2}:
 0.0   1.0  -2.3  0.1
 1.3   4.0  -0.1  0.0
 4.1  -1.0   0.0  1.7

（ここで`Array{Float64,2}`という表示は，配列が2次元でその要素は64ビット浮動小数点数であることを意味している）．上の例では，行列の各行を改行して入力したので，コードが読みやすくなっている．しかし改行する必要はなく以下のコードも全く同じである．

In [2]:
A = [0 1 -2.3 0.1; 1.3 4 -0.1 0; 4.1 -1 0 1.7]

3×4 Array{Float64,2}:
 0.0   1.0  -2.3  0.1
 1.3   4.0  -0.1  0.0
 4.1  -1.0   0.0  1.7

Juliaの関数`size(A)`はサイズをタプルで返す．また`size(A,1)`や`size(A,2)`とすると，行や列の数が得られる．例えば行列が縦長かどうかを判定する関数を作ってみよう．

In [3]:
m, n = size(A)

(3, 4)

In [4]:
m

3

In [5]:
n

4

In [6]:
size(A,1)

3

In [7]:
size(A,2)

4

In [8]:
tall(X) = size(X,1) > size(X,2);

In [9]:
tall(A)

false

この関数は，行数と列数を関係演算子`<`で比較し，真偽値を返す．


### インデキシング

行列`A`の$i,j$要素にアクセスするには`A[i,j]`とする．これを使って要素に新しい値を代入することもできる．

In [10]:
A[2, 3] # Aの2,3要素にアクセス

-0.1

In [11]:
A[1, 3] = 7.5; # Aの1,3要素に7.5を代入

In [12]:
A

3×4 Array{Float64,2}:
 0.0   1.0   7.5  0.1
 1.3   4.0  -0.1  0.0
 4.1  -1.0   0.0  1.7

### 単一インデックス指定

Juliaでは行列の要素にアクセスするときに，インデックスを1つだけ指定する方法もある．この方法を使う時には，Juliaでは列優先で行列が（メモリ上に）格納されていることを知っておく必要がある．つまり行列は，最初の列から順に列がスタックされた1次元配列とみなすことができるのである．例えば，次の行列
$$
Z = 
\begin{bmatrix}
-1 & 0 & 2\\
-1 & 2 & 3
\end{bmatrix}
$$
は，
$$
-1, -1, 0, 2, 2, 3
$$
の順番で格納されている．

ここで`Z[5]`のようにインデックスを1つだけ指定すると，この順番において5番目の要素が取り出されることになる．

In [14]:
Z = [ -1 0 2; -1 2 -3];
Z[5]

2

この記法は一般的な数学的記法ではないため，本書では使わない（Juliaを使うときに便利な場合もある）．

### 行列の等値性

`A == B`は，行列`A`と`B`が等しいかどうかを評価する．式`A .== B`は，`A`と`B`の対応する要素が等しいかどうかを表す真偽値からなる行列を生成する．式`sum(A .== B)`は，`A`と`B`で等しい要素の個数を返す．

In [15]:
B = copy(A);
B[2, 2] = 0;
A == B

false

In [16]:
A .== B

3×4 BitArray{2}:
 true   true  true  true
 true  false  true  true
 true   true  true  true

In [17]:
sum(A .== B)

11

### 行ベクトルと列ベクトル

本書と同様にJuliaでは，$n$次元ベクトルは$n \times 1$行列と同じものである．

In [18]:
a = [ -2.1 -3 0 ]  # 3次元の行ベクトル，1x3行列

1×3 Array{Float64,2}:
 -2.1  -3.0  0.0

In [19]:
b = [ -2.1; -3; 0 ]  # 3次元ベクトル，3x1行列

3-element Array{Float64,1}:
 -2.1
 -3.0
  0.0

出力を見れば多少違いがあることが分かるが，通常は無視しても構わないものである．`b`の型は`Array{Float64,1}`となっていて，`1`はこれが1次元ベクトルであることを意味している．`size(b)`とすると`(3,)`が出力されるが，これは`(3,1)`と同じと考えてよい．つまりJuliaでは，$n \times 1$行列は$n$次元ベクトルと同じである．$n$次元ベクトルは$n \times 1$行列と同じと言った理由はこれである．

### スライシングと部分行列

部分行列を取り出すにはコロン`:`を使う．

In [20]:
A = [ -1 0 1 0 ; 2 -3 0 1 ; 0 4 -2 1]

3×4 Array{Int64,2}:
 -1   0   1  0
  2  -3   0  1
  0   4  -2  1

In [21]:
A[1:2, 3:4]

2×2 Array{Int64,2}:
 1  0
 0  1

これは本書で用いている数学的な記法$A_{1:2, 3:4}$とほぼ同じである．またスライシング（範囲指定）を使って，部分行列を代入することもできる．

インデックスの範囲指定`:`は非常に便利である．これは，そのインデックスのすべての範囲を指定する．これを使えば，行列の行や列を抜き出すことができる．

In [22]:
A[:, 3]  # Aの第3列

3-element Array{Int64,1}:
  1
  0
 -2

In [23]:
A[2, :]  # Aの第2行．ただし列ベクトルで返ってくる！

4-element Array{Int64,1}:
  2
 -3
  0
  1

本書での数学的な記法でいえば，`A[2, :]`は`A`の第2列の転置が返される．

ベクトルの場合と同様に，Juliaのスライシングとインデキシングは，不連続なインデックスを指定することができる．例えば，以下のように行列の行を逆順にすることができる．

In [24]:
X = [ -1 0 1 0 ; 2 -3 0 1 ; 0 4 -2 1]
m = size(X, 1);
X[m:-1:1, :]  # 行が逆順になったX

3×4 Array{Int64,2}:
  0   4  -2  1
  2  -3   0  1
 -1   0   1  0

Juliaの行列の単一インデックス指定は，インデックスの範囲指定や集合でもよい．例えば`X`が$m \times n$行列の場合，`X[:]`は`X`の列を順にスタックした長さ$mn$のベクトルである．Juliaの関数`reshape(X, (k, l))`は，`X`の要素を列優先で並べ直した新しい$k \times l$行列である（ただし$mn=kl$，つまり元の行列と新しい行列の要素数は等しくなければならない）．どちらも数学的な記法ではないが，Juliaでは有用である．

In [25]:
B = [ 1 -3 ; 2 0 ; 1 -2]

3×2 Array{Int64,2}:
 1  -3
 2   0
 1  -2

In [26]:
B[:]

6-element Array{Int64,1}:
  1
  2
  1
 -3
  0
 -2

In [27]:
reshape(B, (2, 3))

2×3 Array{Int64,2}:
 1   1   0
 2  -3  -2

In [28]:
reshape(B, (3, 3))

DimensionMismatch: DimensionMismatch("new dimensions (3, 3) must be consistent with array size 6")

### ブロック行列

ブロック行列をJuliaで作る方法は，本書の数学的な記法とほぼ同じである．セミコロン`;`は行列をスタックし，空白は（横方向に）行列を連結する．以下は本書＊＊ページの例である．


In [29]:
B = [ 0 2 3 ];  # 1x3行列
C = [ -1 ];  # 1x1行列
D = [ 2 2 1 ; 1 3 5 ];  # 2x3行列
E = [ 4 ; 4 ];  # 2x1行列
# 3x4ブロック行列を作る
A = [B C ;
     D E]

3×4 Array{Int64,2}:
 0  2  3  -1
 2  2  1   4
 1  3  5   4

### 行列の行と列の解釈

$m \times n$行列$A$は，$n$個の$m$次元（列）ベクトルの集合，もしくは$m$個の$n$次元（行）ベクトルの集合，とみなすことができる．Juliaでは行列（2次元配列）とベクトルのリストは異なるものである．列ベクトルの配列（もしくはタプル）は，横方向の連結関数`hcat`を使って行列に変換できる．


In [30]:
a = [ [1., 2.], [4., 5.], [7., 8.] ] # 2次元ベクトルの配列

3-element Array{Array{Float64,1},1}:
 [1.0, 2.0]
 [4.0, 5.0]
 [7.0, 8.0]

In [31]:
A = hcat(a...)

2×3 Array{Float64,2}:
 1.0  4.0  7.0
 2.0  5.0  8.0

ここで`hcat(a...)`の中の`...`演算子は，配列`a`を要素に分割する．つまり`hcat(a...)`は`h(a[1], a[2], a[3])`と同じである．この結果，`a[1]`，`a[2]`，`a[3]`が横方向に連結される．

同様に`vcat`は配列を縦方向の連結する．これは行ベクトルから行列を作る場合に便利である．


In [32]:
a = [ [1. 2.], [4. 5.], [7. 8.] ] # 1x2行列の配列

3-element Array{Array{Float64,2},1}:
 [1.0 2.0]
 [4.0 5.0]
 [7.0 8.0]

In [33]:
A = vcat(a...)

3×2 Array{Float64,2}:
 1.0  2.0
 4.0  5.0
 7.0  8.0

## 6.2 ゼロ行列と単位行列

### ゼロ行列

$m \times n$ゼロ行列は`zeros(m,n)`で作成できる．


In [34]:
zeros(2, 2)

2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

### 単位行列

Juliaで単位行列を作る方法はいろいろあり，例えばゼロ行列を作り，対角成分を1にする．
`LinearAlgebra`パッケージには，特殊な単位行列オブジェクト`I`を作る関数がある．$n \times n$単位行列を作成するには`1.0 * Matrix(I, n, n)`とする（1.0をかけるのは，真偽値の行列を数値の行列へ変換するためである）．この式はかなり分かりにくいので，ここでは単位行列を生成する関数`eye(n)`を定義する．この関数は`VMLS`パッケージにも含まれているので，インストールすれば使える（`eye`という名称は，MATLABでも単位行列の関数である）．

In [35]:
using LinearAlgebra

In [36]:
eye(n) = 1.0 * Matrix(I, n, n);
eye(4)

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

Juliaの単位行列`I`には便利な性質がある．例えば，明らかな場合には次元を指定する必要がない（これは一般的な数学的記法と同じである．本書＊＊を参照）．

In [37]:
A = [ 1 -1 2; 0 3 -1]

2×3 Array{Int64,2}:
 1  -1   2
 0   3  -1

In [38]:
[A I]

2×5 Array{Int64,2}:
 1  -1   2  1  0
 0   3  -1  0  1

In [39]:
[A ; I]

5×3 Array{Int64,2}:
 1  -1   2
 0   3  -1
 1   0   0
 0   1   0
 0   0   1

In [40]:
B = [ 1 2 ; 3 4 ]

2×2 Array{Int64,2}:
 1  2
 3  4

In [41]:
B + I

2×2 Array{Int64,2}:
 2  2
 3  5

### 1行列

本書では，要素がすべて1である行列には記号を特に付けていない．Juliaでは`ones(m, n)`で生成できる．

### 対角行列

一般的な数学的記法では$\mathbf{diag}(1,2,3)$は，対角要素が$1,2,3$である$3 \times 3$対角行列を表す．Juliaでは`LinearAlgebra`パッケージの関数`diagm`を使う．ベクトル`s`の要素から対角行列を作るには，`diagm(0 => s)`と書く．これは非常に分かりにくいため，`VMLS`パッケージでは関数`diagonal(s)`を定義している（対角要素のベクトルを引数に取る）．


In [42]:
diagonal(x) = diagm(0 => x)

diagonal (generic function with 1 method)

In [43]:
diagonal([1, 2, 3])

3×3 Array{Int64,2}:
 1  0  0
 0  2  0
 0  0  3

これとは逆のJuliaの関数が`diag(X)`であり，行列`X`（正方行列とは限らない）の対角成分をベクトルで返す．

In [44]:
H = [0 1 -2 1; 2 -1 3 0]

2×4 Array{Int64,2}:
 0   1  -2  1
 2  -1   3  0

In [45]:
diag(H)

2-element Array{Int64,1}:
  0
 -1

### ランダム行列

0から1までのランダムな要素を持つ$m \times n$行列は`rand(m,n)`で生成できる．要素を正規分布から抽出するなら`randn(m,n)`とする．

In [46]:
rand(2, 3)

2×3 Array{Float64,2}:
 0.259206  0.00145257  0.105918
 0.564099  0.256196    0.76442 

In [47]:
randn(2, 3)

2×3 Array{Float64,2}:
 0.396847  -0.156044  -0.0472458
 0.476575  -0.23498   -0.822903 

### 疎行列

疎行列の作成と操作のための関数は`SparseArrays`パッケージに含まれている（インストールが必要．＊＊＊ページ参照）．疎行列は，ほとんどの要素がゼロであるという性質を利用した特殊なフォーマットで保持されている．関数`sparse`は，行のインデックス，列のインデックス，非ゼロ要素の値，の3つの配列から疎行列を作成する．たとえば，疎行列
$$
A = 
\begin{bmatrix}
-1.11 & 0 & 1.17 & 0 & 0\\
0.15 & -0.10 & 0 & 0 & 0\\
0 & 0 & -0.30 & 0 & 0\\
0 & 0 & 0 & 0.13 & 0
\end{bmatrix}
$$
を作成するコードは以下のようになる．

In [48]:
using SparseArrays

In [49]:
K = [1, 2, 2, 1, 3, 4];  # 非ゼロ要素の行のインデックス
J = [1, 1, 2, 3, 3, 4];  # 列のインデックス
V = [ -1.11, 0.15, -0.10, 1.17, -0.30, 0.13 ];  # 値
A = sparse(K, J, V, 4, 5)

4×5 SparseMatrixCSC{Float64,Int64} with 6 stored entries:
  [1, 1]  =  -1.11
  [2, 1]  =  0.15
  [2, 2]  =  -0.1
  [1, 3]  =  1.17
  [3, 3]  =  -0.3
  [4, 4]  =  0.13

In [50]:
nnz(A)  # 非ゼロ要素の個数

6

疎行列は関数`Array`を使って普通の行列に変換することができる．関数`sparse`は普通の行列を疎行列に変換する．


In [51]:
A = sparse([1, 3, 2, 1], 
           [1, 1, 2, 3],
           [1.0, 2.0, 3.0, 4.0], 3, 3)

3×3 SparseMatrixCSC{Float64,Int64} with 4 stored entries:
  [1, 1]  =  1.0
  [3, 1]  =  2.0
  [2, 2]  =  3.0
  [1, 3]  =  4.0

In [52]:
B = Array(A)

3×3 Array{Float64,2}:
 1.0  0.0  4.0
 0.0  3.0  0.0
 2.0  0.0  0.0

In [53]:
B[1, 3] = 0.0;
sparse(B)

3×3 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [1, 1]  =  1.0
  [3, 1]  =  2.0
  [2, 2]  =  3.0

疎な$m \times n$ゼロ行列を作るには`spzeros(m, n)`を使う．疎な$n \times n$単位行列をJuliaで作成するには`sparse(1.0I, n, n)`と書くが，これは分かりにくいため，`VMLS`パッケージでは関数`speye(n)`を定義している．また`VMLS`パッケージには，ベクトル`a`の要素から疎な対角行列を作成する`spdiagonal(a)`も定義してある．

ランダムな疎行列を作成する関数は`sprand(m, n, d)`（要素の範囲は0から1）と`sprandn(m, n, d)`（要素は正規分布から抽出）である．最初の2つの引数は行列の次元である．3つ目の引数`d`は非ゼロ要素の密度を指定し，ランダムに選ばれた約$mnd$個の要素が非ゼロになる．以下のコードでは，密度$d=10^{-7}$で$10000 \times 10000$疎行列を作成している．つまり非ゼロ要素はおよそ10個になる（非常に疎な行列である！）．


In [54]:
A = sprand(10000, 10000, 10^-7)

10000×10000 SparseMatrixCSC{Float64,Int64} with 8 stored entries:
  [9042 ,  2892]  =  0.00307387
  [8971 ,  4810]  =  0.650686
  [7523 ,  5085]  =  0.515843
  [8147 ,  5404]  =  0.112658
  [6700 ,  6289]  =  0.383604
  [873  ,  6290]  =  0.265995
  [3570 ,  7127]  =  0.347568
  [383  ,  7229]  =  0.665205

## 6.3 転置，和，ノルム

### 転置

本書では，$m \times n$行列$A$の転置を$A^T$と表記した．Juliaでは，`A`の転置は`A'`である．

In [55]:
H = [ 0 1 -2 1; 2 -1 3 0 ]

2×4 Array{Int64,2}:
 0   1  -2  1
 2  -1   3  0

In [56]:
H'

4×2 Adjoint{Int64,Array{Int64,2}}:
  0   2
  1  -1
 -2   3
  1   0

### 和，差，スカラー倍

Juliaでは行列の和，差，スカラー倍は一般的な数学的記法と同じである．


In [57]:
U = [ 0 4; 7 0; 3 1]

3×2 Array{Int64,2}:
 0  4
 7  0
 3  1

In [58]:
V = [ 1 2; 2 3; 0 4]

3×2 Array{Int64,2}:
 1  2
 2  3
 0  4

In [59]:
U + V

3×2 Array{Int64,2}:
 1  6
 9  3
 3  5

In [60]:
2.2 * U

3×2 Array{Float64,2}:
  0.0  8.8
 15.4  0.0
  6.6  2.2

（スカラーを行列の右からかけることもできる）

Juliaは一般的な数学的記法とは異なる演算もサポートする．例えばJuliaでは，行列に定数を足したり引いたりすることができる．この場合，行列の各要素にその定数を足したり引いたりする処理になる．

### 要素毎の演算

＊＊＊ページで説明したベクトルの要素毎の演算はそのまま行列にも適用できる．二項演算子の前にドットを付けると，要素毎の演算になる．例えば同じサイズの行列$A$と$B$に対して，`C = A .* B`は同じサイズの行列で要素が$C_{ij} = A_{ij} B_{ij}$となる．関数名の後にドットを付けると関数が要素毎に適用される．`X`が行列ならば，`Y = exp.(X)`は同じサイズの行列で要素は$Y_{ij} = \exp(X_{ij})$となる．

### 行列ノルム

本書では$m \times n$行列のノルム$\| A \|$を次式で定義した．
$$
\| A \| = \left( \sum_{i=1}^m \sum_{j=1}^n A_{ij}^2 \right)^{1/2}
$$
一般的な数学的記法では，これを$\| A \|_F$と書くことが多く（$F$はフロベニウスノルムを意味する），$\| A \|$とだけ書くと他のノルムを意味することが多い（ただし本書の範囲を超える）．Juliaでは，上記のノルムは`norm(A)`で求まる．

In [61]:
A = [2 3 -1; 0 -1 4]

2×3 Array{Int64,2}:
 2   3  -1
 0  -1   4

In [62]:
norm(A)

5.5677643628300215

In [63]:
norm(A[:])

5.5677643628300215

### 三角不等式

三角不等式$\| A + B \| \le \| A \| + \| B \|$をチェックしよう．

In [65]:
A = [ -1 0; 2 2 ];
B = [ 3 1; -3 2 ];
norm(A + B), norm(A) + norm(B)

(4.69041575982343, 7.795831523312719)

## 6.4 行列ベクトル積

Juliaでは行列とベクトルの積は普通に`y = A * x`と書く．


In [66]:
A = [0 2 -1; -2 1 1]

2×3 Array{Int64,2}:
  0  2  -1
 -2  1   1

In [67]:
x = [2, 1, -1]

3-element Array{Int64,1}:
  2
  1
 -1

In [68]:
A * x

2-element Array{Int64,1}:
  3
 -4

### 差分行列

$(n-1)\times n$差分行列（本書の式(6.5)）を作る方法はいくつかある．簡単な方法は次のものである．


In [69]:
difference_matrix(n) = [-eye(n-1) zeros(n-1)] +
                       [zeros(n-1) eye(n-1)];

In [70]:
D = difference_matrix(4)

3×4 Array{Float64,2}:
 -1.0   1.0   0.0  0.0
  0.0  -1.0   1.0  0.0
  0.0   0.0  -1.0  1.0

In [71]:
D * [-1, 0, 2, 1]

3-element Array{Float64,1}:
  1.0
  2.0
 -1.0

difference行列の要素の多くはゼロなので，疎行列にするほうがよい．

In [74]:
using VMLS

In [75]:
difference_matrix(n) = [-speye(n-1) spzeros(n-1)] +
                       [spzeros(n-1) speye(n-1)];

In [76]:
D = difference_matrix(4)

3×4 SparseMatrixCSC{Float64,Int64} with 6 stored entries:
  [1, 1]  =  -1.0
  [1, 2]  =  1.0
  [2, 2]  =  -1.0
  [2, 3]  =  1.0
  [3, 3]  =  -1.0
  [3, 4]  =  1.0

In [77]:
D * [-1, 0, 2, 1]

3-element Array{Float64,1}:
  1.0
  2.0
 -1.0

### 累積和行列

累積和行列（本書の式(6.6)）は，対角成分以下のすべての要素が1の下三角行列である．


In [78]:
function running_sum(n)  # n x n 累積和行列
S = zeros(n,n)
for i=1:n
   for j=1:i
       S[i,j] = 1
   end
end
return S
end

running_sum (generic function with 1 method)

In [79]:
running_sum(4)

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0
 1.0  1.0  1.0  0.0
 1.0  1.0  1.0  1.0

In [81]:
running_sum(4) * [-1, 1, 2, 0]

4-element Array{Float64,1}:
 -1.0
  0.0
  2.0
  2.0

別の方法は`tril(ones(n, n))`を使うことである．この`tril`という関数は対角成分よりも上の要素をすべてゼロにする．

### ヴァンデルモンド行列

$m \times n$ヴァンデルモンド行列（本書の式(6.7)）は，$i=1,\ldots,m, j=1,\ldots,n$について$ij$要素が$t_i^{j-1}$の行列である．以下の関数は，要素が$t_1,\ldots,t_m$である$m$次元ベクトル`t`を引数にとり，それに対応する$m \times n$ヴァンデルモンド行列を返す．


In [83]:
function vandermonde(t,n)
m = length(t)
V = zeros(m,n)
for i=1:m
   for j=1:n
      V[i,j] = t[i]^(j-1)
   end
end
return V
end

vandermonde (generic function with 1 method)

In [84]:
vandermonde([-1,0,0.5,1],5)

4×5 Array{Float64,2}:
 1.0  -1.0  1.0   -1.0    1.0   
 1.0   0.0  0.0    0.0    0.0   
 1.0   0.5  0.25   0.125  0.0625
 1.0   1.0  1.0    1.0    1.0   

Juliaの`hcat`を使う方法もある．

In [85]:
vandermonde(t,n) = hcat( [t.^i for i = 0:n-1]... )

vandermonde (generic function with 1 method)

In [86]:
vandermonde([-1,0,0.5,1],5)

4×5 Array{Float64,2}:
 1.0  -1.0  1.0   -1.0    1.0   
 1.0   0.0  0.0    0.0    0.0   
 1.0   0.5  0.25   0.125  0.0625
 1.0   1.0  1.0    1.0    1.0   

## 6.5 計算量

### 行列ベクトル積の計算量

$m \times n$行列と$n$次元ベクトルとの積の計算量は$2mn$ flopsである．これは$m$と$n$の両方について線形である．これを確認しよう．

In [87]:
A = rand(1000, 10000);
x = rand(10000);

In [88]:
@time y = A * x;

  0.016571 seconds (7.61 k allocations: 429.464 KiB)


In [89]:
@time y = A * x;

  0.007501 seconds (5 allocations: 8.094 KiB)


In [90]:
A = rand(5000, 20000);
x = rand(20000);

In [91]:
@time y = A * x;

  0.089777 seconds (6 allocations: 39.297 KiB)


In [92]:
@time y = A * x;

  0.064207 seconds (6 allocations: 39.297 KiB)


2つ目の行列ベクトル積では，$m$は5倍，$n$は2倍になっており，計算時間は（およそ）10倍になっていると予想できる．ここでは7.4倍程度になっている．

疎行列の計算が効率的であることは差分行列とベクトルとの積を計算してみれば分かる．

In [93]:
n = 10^4;
D = [-eye(n-1) zeros(n-1)] + [zeros(n-1) eye(n-1)];
x = randn(n);

In [94]:
@time y = D * x;

  0.708264 seconds (6 allocations: 78.359 KiB)


In [95]:
@time y = D * x;

  0.055183 seconds (6 allocations: 78.359 KiB)


In [96]:
Ds = [-speye(n-1) spzeros(n-1)] + [spzeros(n-1) speye(n-1)];

In [97]:
@time y = Ds * x;

  0.049030 seconds (52.40 k allocations: 2.741 MiB)


In [98]:
@time y = Ds * x;

  0.000240 seconds (6 allocations: 78.359 KiB)
